inherits = "onedark"

"keyword" = { fg = "purple" }
"punctuation" = { fg = "white" }
"punctuation.special" = { fg = "purple" }
"variable" = { fg = "white" }
"variable.builtin" = { fg = "cyan" }
"ui.virtual.ruler" = { bg = "light-black" }
"ui.bufferline.active" = { fg = "white", bg = "light-black" }

'markup.heading' = { fg = 'blue', modifiers = ['bold'] }
'markup.heading.marker' = { fg = 'grey4' }
'markup.heading.1' = { fg = 'blue', modifiers = ['bold'] }
'markup.heading.2' = { fg = 'red', modifiers = ['bold']  }
'markup.heading.3' = { fg = 'cyan', modifiers = ['bold'] }
'markup.heading.4' = { fg = 'green', modifiers = ['bold'] }
'markup.heading.5' = { fg = 'yellow', modifiers = ['bold'] }
'markup.heading.6' = { fg = 'purple', modifiers = ['bold'] }

[palette]
red = "#d07277ff"
yellow = "#E5C080"
