[[language]]
name = "markdown"
text-width = 100
language-servers = ["harper-ls", "marksman", "markdown-oxide"]

[[language]]
name = "rust"
rulers = [101]
text-width = 100
language-servers = ["rust-analyzer", "harper-ls"]

[[language]]
name = "toml"
auto-format = false
formatter = { command = "taplo", args = ["format", "-"] }

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]
# A config is required to avoid errors 
# See <https://github.com/elijah-potter/harper/blob/master/harper-ls/README.md#configuration>
config = { harper-ls = {} } 

# [language-server.koto-ls]
# command = "koto-ls"

# [[language]]
# name = "koto"
# scope = "source.koto"
# injection-regex = "koto"
# file-types = ["koto"]
# comment-token = "#"
# indent = { tab-width = 2, unit = "  " }
# roots = []
# language-servers = [ "koto-ls" ]

# [[grammar]]
# name = "koto"
# source = { git = "https://github.com/koto-lang/tree-sitter-koto", rev = "main" }
