[[language]]
name = "javascript"
auto-format = true

[[language]]
name = "markdown"
text-width = 100
language-servers = ["harper-ls", "marksman", "markdown-oxide"]

[[language]]
name = "javascript"
auto-format = true

[[language]]
name = "rust"
rulers = [101]
text-width = 100
language-servers = ["rust-analyzer", "harper-ls"]

[[language]]
name = "toml"
auto-format = false
formatter = { command = "taplo", args = ["format", "-"] }

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

# See <https://writewithharper.com/docs/integrations/neovim#Configuration>
[language-server.harper-ls.config.harper-ls]
linters = { an_a = false } 
isolateEnglish = true


# [language-server.koto-ls]
# command = "koto-ls"

# [[language]]
# name = "koto"
# scope = "source.koto"
# injection-regex = "koto"
# file-types = ["koto"]
# comment-token = "#"
# indent = { tab-width = 2, unit = "  " }
# roots = []
# language-servers = [ "koto-ls" ]

# [[grammar]]
# name = "koto"
# source = { git = "https://github.com/koto-lang/tree-sitter-koto", rev = "main" }
