[[language]]
name = "rust"
rulers = [101]
text-width = 100

[[language]]
name = "toml"
auto-format = true
formatter = { command = "taplo", args = ["format", "-"] }

# [language-server.koto-ls]
# command = "koto-ls"

# [[language]]
# name = "koto"
# scope = "source.koto"
# injection-regex = "koto"
# file-types = ["koto"]
# comment-token = "#"
# indent = { tab-width = 2, unit = "  " }
# roots = []
# language-servers = [ "koto-ls" ]

# [[grammar]]
# name = "koto"
# source = { git = "https://github.com/koto-lang/tree-sitter-koto", rev = "main" }
